name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: docker build -t inference-model-git .

    - name: Tag Docker image
      run: |
        docker tag inference-model-git:latest ${{ steps.ecr-login.outputs.registry }}/my-inference-model:latest-git

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ steps.ecr-login.outputs.registry }}/my-inference-model:latest-git

    - name: Update Lambda function
      run: |
        aws lambda update-function-code --function-name cabbage-inference-lambda \
          --image-uri ${{ steps.ecr-login.outputs.registry }}/inference-model-git:latest-git


    # - name: Create or Update Lambda
    #   run: |
    #     aws lambda create-function \
    #       --function-name cabbage-inference-lambda \
    #       --package-type Image \
    #       --code ImageUri=${{ steps.ecr-login.outputs.registry }}/my-inference-model:latest-git \
    #       --role arn:aws:iam::173778668309:role/lambda-exec-role \
    #       --memory-size 2048 \
    #       --timeout 180 \
    #       --region us-east-1




